<?php
	include('includes/header.php');
?>

<div class="about-wrapper">
<div class="container">
	<div class="about-left">
		<ul class="tabs">
			<li>
				<a href="#tab1">
					About Author
				</a>
			</li>
			<li>
				<a href="#tab2">
					About Website
				</a>
			</li>
			<li>
				<a href="#tab3">
					Technical Details
				</a>
			</li>
		</ul>
	</div>
	<div class="nine about-right">
		<div id="tab1">
			<h3>
				About Author
			</h3>
			<h1>
				I am...
			</h1>
			<div class="about-body">
				<p>
					A Designer specializing in user experience, user interface and web development. 
					My most recent experience was at a Tech Startup company as an interaction design intern 
					building the front-end of their website. <br>
					I work well with developers and business professionals 
					to create successful services along with my intuitions and design researches. 
					I love to develop a vision that entire team believes in and 
					I want to challenge myself to problems ahead, taking new and existing products to the next level.
				</p>
			</div>
			
		</div>
		<div id="tab2">
			<h3>
				About website
			</h3>
			<h1>	
				This website is...
			</h1>
			<div class="about-body">
				<blockquote cite='http://www.sfu.ca/siat/about_siat.html'>
					<p>
						We're creating a new community based on integrating theory and application.
					</p>
				</blockquote>
				<p>
					The School of Interactive Art and Technology (SIAT) at SFU is an interdisciplinary research focused school where technologists, artists, designers and theorists collaborate in innovative research and immersive study. 
				</p>
				
				<p>
					A degree in Interactive Arts and Technology prepares students to play a leading role in the conception of new media and the design of inventive technologies. 
					A SIAT education combines the science of human experience, the analysis of media and culture, the creation of original and experimental works of art, and the implementation of new technologies.
					Students bring these resources to bear on the most vital and innovative sectors of the economy, building the technologies and experiences that increasingly shape our lives.
				</p>
				<p>
					Central to the notion of this website is connecting current students and alumni of SIAT (members) to people looking for higher education in this field (visitors). 
					In order for people to better understand about SIAT, this website allows members to share their thoughts, ideas, experience and interests through their blog posts, Twitter timeline and Flickr Photostream.
				</p>
				<p>
					Once visitors sign up for our service, they can easily follow and un-follow our members without any limitation and receive updates about the members on their own personal timeline. 
					Receiving up-to-date information from members is especially important to our website because the field of technology is changing rapidly and most of our members are in the field where they constantly learn new knowledge and skills. 
					Therefore, visitors can easily comprehend not only the field of their interests but also how people from SIAT program live their life after their higher education in Simon Fraser University.  
				</p>
			</div>
		</div>
		<div id="tab3">
			<h3>
				Technical Details
			</h3>
			<h1>	
				Our services provide..
			</h1>
			<div class="about-body">
				<div>
					<span>
						Members
					</span>
					<ul>
						<li>
							<!-- <P> -->
								Write a blog post
							<!-- </P> -->
							
						</li>
						<li>
							<!-- <p> -->
								Connect their Twitter timeline
							<!-- </p> -->
						</li>
						<li>
							<!-- <p> -->
								Connect their Flickr Photostream
							<!-- </p> -->
						</li>
					</ul>
				</div>
				<div>
					<span>
						Visitors
					</span>
					<ul>
						<li>
							<!-- <p> -->
								Follow and un-follow members
							<!-- </p> -->
							
						</li>
						<li>
							<!-- <p> -->
								Receive suggested members' lists which are generated by the
								members' same secondary school visitors are already following
							<!-- </p> -->
						</li>
						<li>
							
								Receive email updates once new blog is posted by the following members
							
						</li>
					</ul>
				</div>
				<div>
					<span>
						Common features
					</span>
					<ul>
						<li>
							
								Share blog posts on twitter
							
						</li>
						<li>
							
								Register their accounts
							
						</li>
						<li>
							
								Sign up and Log in
							
							
						</li>
						<li>
							
								Store results of database queries for better performance in individual member’s timeline.
							
							
						</li>
						<li>
							
								Live search of blog posts
							
						</li>
						<li>
							
								Publish their profile pictures
							
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

</div>

<script type="text/javascript">
	$(document).ready(function(){
		 $('ul.tabs').each(function(){
    // For each set of tabs, we want to keep track of
    // which tab is active and it's associated content
    var $active, $content, $links = $(this).find('a');

    // If the location.hash matches one of the links, use that as the active tab.
    // If no match is found, use the first link as the initial active tab.
    $active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
    $active.addClass('active');

    $content = $($active[0].hash);

    // Hide the remaining content
    $links.not($active).each(function () {
      $(this.hash).hide();
    });

    // Bind the click event handler
    $(this).on('click', 'a', function(e){
      // Make the old tab inactive.
      $active.removeClass('active');
      $content.hide();

      // Update the variables with the new link and content
      $active = $(this);
      $content = $(this.hash);

      // Make the tab active.
      $active.addClass('active');
      $content.show();

      // Prevent the anchor's default click action
      e.preventDefault();
    });
  });
	});
</script>

<?php
	include("includes/footer.php")
?>